---
- hosts: all
  name: Simple nginx example Ansible Local
  become: yes

  - name: Install nginx
    yum:
      name: nginx
      state: present
    
  - name: Create a file with the content 'hello world'.
    copy:
      content: "Hello, World"
      dest: /usr/share/nginx/html/index.html

  - name: Start NGiNX
    service:
      name: nginx
      state: started

