---
- hosts: 127.0.0.1
  connection: local
  name: configuration play
  user: ubuntu

  tasks:
  - name: Install nginx
    yum:
      name: nginx
      state: present
    
  - name: Create a file with the content 'hello world'.
    copy:
      content: "Hello, World"
      dest: /var/www/html/index.html

  - name: Start NGiNX
    service:
      name: nginx
      state: started


